### ISSUE TITLE
Install dev version from github fails

### ISSUE THREAD

**Issue by david-jankoski** [hannesmuehleisen/MonetDBLite-R#1]
Tried to install dev version from here by following the instructions, seems like something is missing when cloning the repo.

```
davidjankoski@davidjankoski-ubuntu:~⟫ git clone https://github.com/hannesmuehleisen/MonetDBLite-R.git --depth 1 --recursive

Cloning into 'MonetDBLite-R'...
remote: Counting objects: 53, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 53 (delta 0), reused 39 (delta 0), pack-reused 0
Unpacking objects: 100% (53/53), done.
Submodule 'src/monetdblite' (https://github.com/hannesmuehleisen/MonetDBLite-C) registered for path 'src/monetdblite'
Cloning into '/home/davidjankoski/MonetDBLite-R/src/monetdblite'...
remote: Counting objects: 474, done.
remote: Compressing objects: 100% (432/432), done.
remote: Total 474 (delta 90), reused 128 (delta 41), pack-reused 0
Receiving objects: 100% (474/474), 2.24 MiB | 718.00 KiB/s, done.
Resolving deltas: 100% (90/90), done.
error: no such remote ref 86c9c223716fedb4545ee1edc58fc2a92cd63de3
Fetched in submodule path 'src/monetdblite', but it did not contain 86c9c223716fedb4545ee1edc58fc2a92cd63de3. Direct fetching of that commit failed.

davidjankoski@davidjankoski-ubuntu:~⟫ R CMD INSTALL MonetDBLite-R

* installing to library ‘/home/davidjankoski/R/x86_64-pc-linux-gnu-library/3.4’
* installing *source* package ‘MonetDBLite’ ...
** libs
make: *** No rule to make target 'build/debug/monetdblite/common/stream.o', needed by 'MonetDBLite.so'.  Stop.
ERROR: compilation failed for package ‘MonetDBLite’
* removing ‘/home/davidjankoski/R/x86_64-pc-linux-gnu-library/3.4/MonetDBLite’
* restoring previous ‘/home/davidjankoski/R/x86_64-pc-linux-gnu-library/3.4/MonetDBLite’
```
thanks. david.

**Comment by ajdamico** [comment]
also fails on windows

	> devtools::install_github("hannesmuehleisen/MonetDBLite-R")
	Downloading GitHub repo hannesmuehleisen/MonetDBLite-R@master
	from URL https://api.github.com/repos/hannesmuehleisen/MonetDBLite-R/zipball/master
	Installing MonetDBLite
	"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/anthonyd/AppData/Local/Temp/Rtmp46TpkG/devtools23a054b0abf/hannesmuehleisen-MonetDBLite-R-13784ad"  \
	  --library="C:/Users/anthonyd/Documents/R/win-library/3.4" --install-tests 

	* installing *source* package 'MonetDBLite' ...
	** libs

	*** arch - i386
	make: *** No rule to make target `build/objects/monetdblite/common/stream.o', needed by `MonetDBLite.dll'.  Stop.
	Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-34~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.2/share/make/winshlib.mk" SHLIB="MonetDBLite.dll" ' had status 2
	ERROR: compilation failed for package 'MonetDBLite'
	* removing 'C:/Users/anthonyd/Documents/R/win-library/3.4/MonetDBLite'
	* restoring previous 'C:/Users/anthonyd/Documents/R/win-library/3.4/MonetDBLite'
	Installation failed: Command failed (1)
	Warning message:
	GitHub repo contains submodules, may not function as expected!

**Comment by hannesmuehleisen** [comment]
Is this still an issue? @david-jankoski without devtools?

**Comment by david-jankoski** [comment]
hey Hannes,

I can confirm that it works now on win - it just cloned succesfully where it previously reported some missing things. 

```
C:\Users\David_Jankoski\Desktop\monetdb_test>git clone https://github.com/hannesmuehleisen/MonetDBLite-R.git --depth 1 --recursive
Cloning into 'MonetDBLite-R'...
remote: Counting objects: 53, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 53 (delta 0), reused 33 (delta 0), pack-reused 0
Unpacking objects: 100% (53/53), done.
Submodule 'src/monetdblite' (https://github.com/hannesmuehleisen/MonetDBLite-C) registered for path 'src/monetdblite'
Cloning into 'C:/Users/David_Jankoski/Desktop/monetdb_test/MonetDBLite-R/src/monetdblite'...
remote: Counting objects: 474, done.
remote: Compressing objects: 100% (431/431), done.
remote: Total 474 (delta 92), reused 116 (delta 42), pack-reused 0
Receiving objects: 100% (474/474), 2.24 MiB | 2.09 MiB/s, done.
Resolving deltas: 100% (92/92), done.
Submodule path 'src/monetdblite': checked out 'ae37c7ae39f2101b2b4920586fe20c9eddd53478'
```
