### ISSUE TITLE
Add wrapper for `cor()`

### ISSUE THREAD

**Issue by edgararuiz** [hannesmuehleisen/MonetDBLite-R#18]
It looks like `cor()` can be supported by translating it to CORR, a straight copy of what is in the PostgreSQL translation in `dbplyr` should work:

- https://github.com/tidyverse/dbplyr/blob/4e868ee2098341941d0560e388b0697e22ac87de/R/db-postgres.r#L74

And here:

- https://github.com/tidyverse/dbplyr/blob/4e868ee2098341941d0560e388b0697e22ac87de/R/db-postgres.r#L86

**Comment by hannesmuehleisen** [comment]
Will add, thanks.
