### ISSUE TITLE
Add support for more window functions

### ISSUE THREAD

**Issue by edgararuiz** [hannesmuehleisen/MonetDBLite-R#19]
I'm getting a warning everytime I run a query using `dplyr`.  It looks like `median` needs to be added to the window functions:

```r
Warning message:
Translator is missing window variants of the following aggregate functions:
* median
```

The message makes sense because I can see the function in the `aggregate` section:

https://github.com/hannesmuehleisen/MonetDBLite-R/blob/master/R/dplyr.R#L28

But is not in the `window` section.

**Comment by hannesmuehleisen** [comment]
Its not in the window section because MonetDB[Lite] does only have limited window functions support.

**Comment by hannesmuehleisen** [comment]
MIN/MAX/SUM/MEDIAN/AVG
Anything I forgot?

**Comment by edgararuiz** [comment]
Ok, I'm just getting `median` in the message, so I'm not sure if adding the other would hurt/help.  BTW - Not sure if this is what you plan to do, but I believe that adding `win_absent()` will both cover the message and let the user that `median` is not supported for windowed functions

**Comment by hannesmuehleisen** [comment]
great  idea, thanks, added
