### ISSUE TITLE
[request] support for integer64 from bit64 package

### ISSUE THREAD

**Issue by dselivanov** [hannesmuehleisen/MonetDBLite-R#2]
Would be great to have support for mapping of R's `bit64::integer64` to monetdb `BIGINT`. (I believe this is quite simple since `bit64::integer64` is just `long long` and I'm pretty sure same as `BIGINT`)

I can't find a solution how to keep `integer64`. Is there any workaround?

**Comment by hannesmuehleisen** [comment]
We will add this at some point. The workaround now is a CAST to string before the result column is handed over.

**Comment by hannesmuehleisen** [comment]
Want to give it a try? I'd be happy to review a PR.

**Comment by dselivanov** [comment]
Can'r promise, but mb will try to create PR this weekend.

**Comment by hannesmuehleisen** [comment]
Referencing a DBI issue on the topic here: https://github.com/r-dbi/DBI/issues/248

**Comment by dselivanov** [comment]
Awesome! I will test and report back.

**Comment by dselivanov** [comment]
@hannesmuehleisen works perfectly. Many thanks!

**Comment by hannesmuehleisen** [comment]
Extended to support `dbConnect` parameter `bigint` as standardized by `DBI`:

````R
library(bit64)
library(DBI)
con <- dbConnect(MonetDBLite::MonetDBLite(), bigint="integer64")
a <- data.frame(a=as.integer64(c(42, NA, 4294967294)))
dbWriteTable(con, "a", a)
print(res <- dbGetQuery(con, "SELECT * from a"))
print(str(res))
````
