### ISSUE TITLE
MonetDBLite installation

### ISSUE THREAD

**Issue by edalmeida** [hannesmuehleisen/MonetDBLite-R#22]
Hi all,

I'm trying to install monetdblite in a fresh Linux Mint machine following your pointers at https://www.monetdb.org/blog/monetdblite-r, but lots of issues came up.
I actually solved them, but I'm not sure it was the best solution. I'll sum them up next.
$ sudo -i R

Fresh MonetDB-Lite install with the following errors:
> install.packages("MonetDBLite")
---- error: "zutil.h:21:22: fatal error: string.h: No such file or directory"
According to link: https://stackoverflow.com/questions/25184167/
It appears to be missing stdlib.h as well as stdio.h
These are standard C headers, that are found in the libc package.

SOLUTION:
$ sudo apt-get install libc6-dev

back to R
$ sudo -i R
> install.packages("dplyr")
---- Error in library(dplyr) : there is no package called ‘dplyr’

Issue solved in: https://github.com/tidyverse/dplyr/issues/2261
> install.packages("devtools")
> install.packages("Rcpp")
---- ERROR: compilation failed for package ‘Rcpp’  (no g++ at this point. Remember the fresh install)

$ apt-get install zlib1g-dev libssl-dev libssh2-1-dev libcurl4-openssl-dev g++

back to R
$ sudo -i R
> install.packages("dplyr")

Now I figured that you meant "dbplyr", instead of "dplyr" when I got this:
> ms <- MonetDBLite::src_monetdblite(dbdir)
---- Error in loadNamespace(name) : there is no package called ‘dbplyr’
> install.packages("dbplyr")

Now, the example works at monetdblite-r link 

Hope this helps you improving monetdb (great project, btw).

cheers,
Eduardo

**Comment by hannesmuehleisen** [comment]
Thanks for pointing this out, but for the source compilation a working compiler with standard library is assumed to be present.
