### ISSUE TITLE
devtools install error

### ISSUE THREAD

**Issue by ajdamico** [hannesmuehleisen/MonetDBLite-R#3]
https://github.com/ajdamico/asdfree/issues/297#issuecomment-337394552

@jeffrosenblum  what is your `sessionInfo()` when this happens?  thanks

**Comment by jeffrosenblum** [comment]
```
> sessionInfo() 
R version 3.4.2 (2017-09-28)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lodown_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13      knitr_1.17        bindr_0.1         xml2_1.1.1       
 [5] magrittr_1.5      hms_0.3           rvest_0.3.2       archive_1.0.0    
 [9] R6_2.2.2          rlang_0.1.2       stringr_1.2.0     httr_1.3.1       
[13] dplyr_0.7.4       tools_3.4.2       DBI_0.7           selectr_0.3-1    
[17] digest_0.6.12     assertthat_0.2.0  tibble_1.3.4      bindrcpp_0.2     
[21] readr_1.1.1       codetools_0.2-15  curl_3.0          glue_1.1.1.9000  
[25] MonetDBLite_0.4.1 haven_1.1.0       stringi_1.1.5     compiler_3.4.2   
[29] forcats_0.2.0     XML_3.98-1.9      pkgconfig_2.0.1  
> 
```

**Comment by david-jankoski** [comment]
dunno if you have seen the issue i opened as well (#1), seems like it is the same problem.

all the best,
david

**Comment by hannesmuehleisen** [comment]
Devtools does not support submodules at this point. So please us the documented method to install the GH version in the meantime.

**Comment by ajdamico** [comment]
sorry, how do windows users install the dev version?

**Comment by hannesmuehleisen** [comment]
Install git? https://git-scm.com/download/win

**Comment by ajdamico** [comment]
sorry, your instructions do not work on windows


	c:\Users\anthonyd>git clone https://github.com/hannesmuehleisen/MonetDBLite-R.git --depth 1 --recursive
	Cloning into 'MonetDBLite-R'...
	remote: Counting objects: 53, done.
	remote: Compressing objects: 100% (52/52), done.
	remote: Total 53 (delta 0), reused 34 (delta 0), pack-reused 0
	Unpacking objects: 100% (53/53), done.
	Submodule 'src/monetdblite' (https://github.com/hannesmuehleisen/MonetDBLite-C) registered for path 'src/monetdblite'
	Cloning into 'C:/Users/anthonyd/MonetDBLite-R/src/monetdblite'...
	remote: Counting objects: 474, done.
	remote: Compressing objects: 100% (431/431), done.
	remote: Total 474 (delta 92), reused 116 (delta 42), pack-reused 0
	Receiving objects: 100% (474/474), 2.24 MiB | 925.00 KiB/s, done.
	Resolving deltas: 100% (92/92), done.
	error: no such remote ref 10e38d95c9e6097f54502bef70a1b69633c02daf
	Fetched in submodule path 'src/monetdblite', but it did not contain 10e38d95c9e6097f54502bef70a1b69633c02daf. Direct fetching of that commit failed.


	c:\Users\anthonyd>"C:\Program Files\R\R-3.4.2\bin\x64\R.exe" CMD INSTALL MonetDBLite-R
	* installing to library 'C:/Users/anthonyd/Documents/R/win-library/3.4'
	* installing *source* package 'MonetDBLite' ...
	** libs

	*** arch - i386
	make: *** No rule to make target `build/objects/monetdblite/common/stream.o', needed by `MonetDBLite.dll'.  Stop.
	Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-34~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.2/share/make/winshlib.mk" SHLIB="MonetDBLite.dll" ' had status 2
	ERROR: compilation failed for package 'MonetDBLite'
	* removing 'C:/Users/anthonyd/Documents/R/win-library/3.4/MonetDBLite'
	* restoring previous 'C:/Users/anthonyd/Documents/R/win-library/3.4/MonetDBLite'
