### ISSUE TITLE
String concatenation

### ISSUE THREAD

**Issue by jcnsilva** [hannesmuehleisen/MonetDBLite-R#30]
Does the library support any string concatenation function? 
I have seen that MonetDB offer support to string concatenation methods, but I've tried using `paste`, `paste0`, `str_c` and `cat` and no one seems to be supported by the library.

As an example, using `paste` inside a mutate throws an error.

This is the code I'm executing:
``` r
elections <- tbl(monet_connection, 'elections') %>%
  distinct()
elections <- elections %>%
  rename(name = election_description)
elections <- elections %>%
  mutate(name = toupper(name))
elections <- elections %>%
  mutate(name = paste('test', year)) %>% 
  collect()
```

The query generated by `explain` is:
``` sql
SELECT "year", PASTE('test', "year") AS "name"
FROM (SELECT "year", UPPER("name") AS "name"
FROM (SELECT "year", "election_description" AS "name"
FROM (SELECT DISTINCT *
FROM "elections") "xjjnkzodlb") "hfvbvasaux") "yhkoodzuan"
```

And the resulting error is

`Error in .local(conn, statement, ...) : 
  Unable to execute statement 'SELECT "year", PASTE('test', "year") AS "name"
FROM (SELECT "year", UPPER("name") AS "name"
FROM (SE...'.
Server says 'ParseException:SQLparser:42000!SELECT: no such binary operator 'paste(char,int)''.`

**Comment by hannesmuehleisen** [comment]
So in SQL you would use the `concat` function or the `||` operator to concatenate strings. For dbplyr, I think this mapping for `paste`  is missing.  This is however also true for RSQLite for example. So I think this is an issue to be raised in dbplyr so it can be fixed for all databases.

````
library(dplyr)
library(DBI)
s <- src_sqlite("/tmp/fuu", create=T)
dbWriteTable(s$con, "mtcars", mtcars)
t <- tbl(s, "mtcars")
t %>% mutate(name=paste('asdf', as.character(cyl)))
Error in result_create(conn@ptr, statement) : no such function: PASTE
````
this works however
````
dbGetQuery(s$con, "SELECT 'asdf-' || mpg FROM mtcars")
   'asdf-' || mpg
1       asdf-21.0
2       asdf-21.0
3       asdf-22.8
4       asdf-21.4
5       asdf-18.7
6       asdf-18.1
7       asdf-14.3
````

**Comment by jcnsilva** [comment]
Got it. It seems to be a problem with some databases, since it works with MySQL / MariaDB
Thanks for the response, I'm closing the issue. :smile:
