### ISSUE TITLE
Error connecting to database when src_monetdb object exists in Global Environment

### ISSUE THREAD

**Issue by nilescbn** [hannesmuehleisen/MonetDBLite-R#31]
I've been very intrigued by the promise of the `MonetDBLite` with `dplyr` combo. However, problems with fatal error messages have kept me from using it more routinely. Picking it back up today, I thought I had figured out my problem and posted the following StackOverflow answer:

https://stackoverflow.com/a/53307673/3705612

To save people from needing to read that response, the error messages I receive are similar to this one:

>Error in UseMethod("db_query_fields") : no applicable method for 'db_query_fields' applied to an object of class "MonetDBEmbeddedConnection"

I've seen more than just "db_query_fields" come up. For example, if I try and run a dplyr query on using the tbl object, I get an `Error in UseMethod("db_sql_render")` message instead.

After digging into it more, I've lost confidence in my theory that the order of package loading was the culprit. I'm now thinking the error arises simply from the fact that I load an R session with a `src_monetdb` object already in the Global Environment. As long as I load an R session with an empty Environment, I can load `MonetDBLite` before `dplyr` and `dbplyr`.

I use `monet_shutdown()` before restarting the R Session. Yet that doesn't seem to help.  If the src_monetdb object is in the Global Environment on startup, I get the error.

So while I'm guessing this is not a bug, I was hoping to track down why this is happening. I've been using R, and very gratefully, for a few years now but the magic behind `DBI` , `MonetDBILite`, `dbplyr`, etc. is exactly that to me---I don't understand the intricacies of how they work. Please excuse me if I'm missing something obvious. 

My session info is pasted below. I'm been using RStudio Version 1.2.1060 while investigating the issue. I also tried using the standard R Gui, making sure to save the src_monetdb object into the workspace, but could not reproduce the error there. 

>R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dbplyr_1.2.2      dplyr_0.7.8       DBI_1.0.0        
[4] MonetDBLite_0.6.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       codetools_0.2-15 crayon_1.3.4     packrat_0.4.9-3 
 [5] digest_0.6.18    assertthat_0.2.0 R6_2.3.0         magrittr_1.5    
 [9] pillar_1.3.0     rlang_0.3.0.1    rstudioapi_0.8   bindrcpp_0.2.2  
[13] tools_3.5.1      glue_1.3.0       purrr_0.2.5      compiler_3.5.1  
[17] pkgconfig_2.0.2  tidyselect_0.2.5 bindr_0.1.1      knitr_1.20      
[21] tibble_1.4.2

**Comment by hannesmuehleisen** [comment]
Hmm, if its not reproducible in standard R its going to be a bit tricky. The order of package loading should not really matter. What do you mean by having the src_monetdb in the global environment? Is that a saved environment?

**Comment by nilescbn** [comment]
Thank you for the quick reply. And, yes, while I can reproduce the error on my own computer I recognize it may not be easy or possible for others to investigate. I appreciate your time. 

On the Global Environment, yes what I meant was that the .RData file is restored at startup. Here's a screenshot of the RStudio project where I've experienced the errors. This is what it looks like at startup when RStudio is set to restore .RData into the workspace at startup. 
![image](https://user-images.githubusercontent.com/9826806/48572896-99b56680-e8bf-11e8-9934-73e2ce971575.png)

If I clear the workspace with `rm(list = ls()` and restart the R session or set RStudio's options to not restore .RData into the workspace at startup, then I have no problems.

On the package load order, the idea came from [an issue jjallaire filed for sparklyr](https://github.com/rstudio/sparklyr/issues/38) where he was getting an `Error in UseMethod("db_query_fields")` message. He wrote:  "Perhaps there is a package load order fiasco of some kind?" He also noted that sparklyr was attached and loaded at startup.

**Comment by hannesmuehleisen** [comment]
So, the src object should never be loaded from the .RData file, it contains pointers which will be invalid at this point. So what happens if you create the src object from scratch before anything else?

**Comment by nilescbn** [comment]
Okay, thanks, that must be it then. I have not seen that be an issue with other database backends in R. 

To your question, if the workspace is empty, then creating the object from scratch with `src_monetdblite()` works. Running the `src_monetdblite()` command with the src object already loaded is when I see the error.  I have to restart the session to get it work. Removing the object and creating it again without a new session also gives me the error.  

I should also have noted that the error message I included in the initial post comes up when trying to connect to the object with `tbl()` The specific error when calling the src object itself is:

```
Error in UseMethod("db_desc") : 
  no applicable method for 'db_desc' applied to an object of class "MonetDBEmbeddedConnection"
```

So it was these "Error in UseMethods" messages made me think there was some compatibility issue with `dbplyr` or `DBI`. Yet now I will just make sure to start with a fresh workspace. Thanks again.
